### ISSUE TITLE
PNPM support

### ISSUE THREAD

**Issue by ShenQingchuan** [rzhAvenir/taro-vue3-template#1]
请问大佬 是否考虑把模板换为 pnpm ?

**Comment by l1m2e** [comment]
+1

**Comment by razzh7** [comment]
已经将yarn替换成pnpm，webpack4升级为webpack5。

**Comment by ShenQingchuan** [comment]
Taro v3.5.4 运行

提示 ：缺少npm包@tarojs/mini-runner，开始安装...
然后会安装失败

**Comment by razzh7** [comment]
@ShenQingchuan 大佬，又更新了一版，你再试下
