### ISSUE TITLE
添加 unocss 375 deviceRatio

### ISSUE THREAD

**Issue by MellowCo** [rzhAvenir/taro-vue3-template#3]
* taro config 中使用 `designWidth: 375`
![image](https://user-images.githubusercontent.com/47939250/187026896-db191be5-3433-41b4-9997-d972412846b4.png)

* 在 `unocss.config.ts` 中 添加 375 的换算尺寸标准，这样可以将 `px` 按照标准，转换成 `rpx`  和 `rem`，与 [taro](https://taro-docs.jd.com/taro/docs/size) 换算标准保持一致
```ts
import { defineConfig } from 'unocss'
import presetWeapp from 'unocss-preset-weapp'
export default defineConfig({
  presets: [
    presetWeapp({
      isH5: process.env.TARO_ENV === 'h5',
      platform: 'taro',
      taroWebpack: 'webpack5',
      designWidth: 375,
      deviceRatio: {
        375: 2 / 1
      },
    })
  ]
})
```

**Comment by razzh7** [comment]
感谢指正，已添加
